generate_module_outline:
  agent: instructional_architect
  description: >
    As the Senior Instructional Architect, your primary task is to generate a detailed module outline for a
    technical (with coding) or non-technical module.
    This includes creating sections for the Instructor Read-Only Overview & Agenda,
    Learner Persona and Prerequisites, High-Level and Detailed Learning Objectives, individual Microlesson
    structures (Title, Learning Objective, Theory, Activity).

    Your process should involve the following steps, informed by the provided {module_topic} and {learner_persona}:

    1.  Define Module Title: Use the provided {module_title}.

    2.  Analyze Inputs and Infer Context:
            - Review the provided {module_topic}, {learner_persona}, and any {learning_objectives}. 
        From these, infer:
            - Appropriate technical or domain prerequisites
            - Learner motivations, goals, and challenges
            - Real-world contexts and examples relevant to the topic

    3. Design Microlesson Structure:
            - Determine the number and sequence of microlessons based on number of {learning_objectives} provided. 
        For each microlesson:
            -Create a concise title
            -Outline key theoretical concepts to be introduced
            -Design a practical, engaging, and contextually appropriate activity
            -Include a method for learners to check their understanding (e.g., a multiple-choice question, coding prompt, or reflection)

    4. Populate the Outline with Clear, Industry-Relevant Content:
            - For each microlesson, provide a detailed overview of the key topics to be covered. 
        These topics should be:
            - Directly aligned with the microlesson’s learning objective
            - Drawn from current industry practices, tools, and knowledge
            - Selected to build progressively toward the overall module goal
            - Use descriptive subsection names that reflect the actual content (e.g., “Model Evaluation Metrics” or “Using Git Branches”), rather than generic structural labels like “Theory” or “Activity.”
            - Include estimated time durations for each microlesson. These estimates should reflect realistic pacing for remote or hybrid delivery, keeping {learner_persona} in mind, including time for guided practice and learner interaction.
            - Ensure each microlesson balances conceptual understanding and practical application, tied clearly to industry-relevant skills and tasks.

    5. Embed Best Practices:
        - Ensure alignment with GA's adult learning theory as outlined in "general_assembly_learning_philosophy" and curriculum design best practices
        - Keep theory concise and actionable
        - Make activities highly relevant and tool-aligned with {tools}.
        - Ensure accessibility for remote learners

  expected_output: >
    A comprehensive module outline in Markdown format, structured according to the following. 
    The outline should include the following sections with detailed content:

    -   **Instructor Read-Only Overview & Agenda:**
        -   Overview: A brief summary of the module's purpose and structure.
        -   Agenda: A list of **generated** microlesson titles with estimated times in "[ ]".
        -   Required Tools: List of necessary software as defined in {tools}.
    -   **Learner Persona and Prerequisites:**
        -   Learner Persona: A description of the target audience (using the provided {learner_persona}).
        -   Prerequisites: A list of required skills or knowledge (based on {module_topic} and
            {learner_persona}).
    -   **Learning Objectives and Outcomes:**
        -   High-Level Learning Goal: A sentence stating the module's main purpose (generated based on
            {module_topic}).
        -   Detailed Learning Objectives: A bulleted list of provided {learning_objectives}
    -   **Module Structure: Microlessons:**
        -   For each **generated** microlesson:
            -   Title: With estimated time in "[ ]". For example : "Introduction to APIs [15 min]"
            -   Learning Objective
            -   Theory: A brief outline of the key concepts.
            -   Activity: A preliminary idea for a hands-on exercises or discussion.

develop_microlesson_content:
  agent: subject_matter_expert
  output_file: output/microlesson-content-from-sme.md
  description: >
    Leveraging your deep expertise in the {module_topic}, take the provided module outline (generated by the
    instructional_architect) as your primary input. Your core task is to develop comprehensive, accurate, and
    engaging content for EACH microlesson defined within that outline. For every microlesson specified, you must:
    1.  **Expand the 'Theory' section:** Provide clear, detailed explanations of the key concepts outlined for
        that microlesson. Break down complex ideas into digestible parts suitable for the target
        {learner_persona}. Include relevant examples, code snippets (if applicable to the {module_topic}),
        diagrams, or analogies to illustrate the concepts effectively. Ensure explanations are structured to
        facilitate effective knowledge checks.
    2.  **Refine and Detail the 'Activity' section:** Transform the preliminary activity idea into a fully
        realized, step-by-step interactive exercise. Ensure the activity directly supports the specific learning
        objective of the microlesson and contributes to the overall module {learning_objectives}. Specify clear,
        actionable deliverables and refine the discussion prompt to be engaging and relevant to the
        {learner_persona}'s context.
    3.  **Develop 'Instructor Speaker Notes & Knowledge Checks':** Write detailed guidance for the instructor.
        Include suggested phrasing, potential student questions or common points of confusion to anticipate, and
        key takeaways to emphasize for each theory segment or activity. Crucially, formulate 1-2 specific, clear
        Knowledge Check questions per microlesson, designed for chat or discussion, that directly verify
        understanding of the core concepts just presented.
    Ensure all generated content is technically accurate for the {module_topic}, maintains an engaging tone, and
    is appropriately paced and scaffolded for the specified {learner_persona}.
  expected_output: >
    A detailed Markdown document containing the fully developed content for **all** microlessons listed in the
    input module outline. The output document should meticulously follow the structure provided by the input
    outline, replacing the initial brief descriptions with comprehensive, ready-to-use content.

    For each microlesson from the input outline (e.g., "Microlesson X: [Title] [Time]"), the output must include:

    * **Learning Objective:** (As defined in the input outline for that specific microlesson)
    * **Detailed Theory:**
        * Clear, paragraph-based explanations of each concept pertinent to the microlesson objective.
        * Formatted examples (e.g., code snippets if the {module_topic} is technical, practical scenarios,
            visual descriptions if applicable).
        * Explanations tailored to the {learner_persona}, defining jargon or simplifying complex terms.
    * **Detailed Activity:**
        * Numbered, step-by-step instructions for the hands-on task or interactive element.
        * A clearly defined Deliverable (e.g., "Post your code snippet to the chat," "Share your summary on the
            whiteboard," "Be prepared to explain your result").
        * A refined and thought-provoking Discussion Prompt related to the activity and relevant to the
            {learner_persona}.
    * **Detailed Instructor Speaker Notes & Knowledge Checks:**
        * Bulleted list of specific talking points, transitions, and potential elaborations for the instructor.
        * Notes on anticipated student difficulties or questions related to the {module_topic}.
        * 1-2 explicitly phrased Knowledge Check questions formatted for interactive delivery (e.g., "Knowledge
            Check (Chat): Based on concept Y, what would be the first step to achieve Z?", "Knowledge Check
            (Discussion): Can someone explain concept X in their own words?").

    The final Markdown output must represent complete, accurate, and engaging instructional content for the core
    microlesson sections, fully aligned with the {module_topic}, {learner_persona}, and {learning_objectives}.

enhance_microlesson_engagement:
  agent: learning_experience_designer
  output_file: output/enhanced-microlesson-content.md
  description: >
    As the Learning Experience Designer, your task is to take the detailed microlesson content generated by the
    subject_matter_expert and significantly enhance its engagement and interactivity for the {learner_persona}.
    Leveraging your expertise in instructional design psychology and the provided resources, you will refine the
    content to create a more memorable and impactful learning journey. For each microlesson, you must:

    1.  **Incorporate Interactive Elements:** Review the 'Theory' and 'Activity' sections and identify opportunities
        to weave in more interactive elements. This could include suggesting interactive questions for the instructor
        to pose during the theory, recommending the use of specific collaborative tools (beyond basic chat and
        VS Code, if appropriate), or proposing mini-challenges or polls to increase learner participation. Ensure
        these elements align with the {learner_persona}'s learning preferences and the remote learning environment.

    2.  **Apply Storytelling and Narrative Techniques:** Where appropriate and relevant to the {module_topic} and
        {learner_persona}, introduce storytelling elements, analogies, or relatable narratives to make the content
        more memorable and create emotional connections. Ensure these techniques enhance understanding and do not
        distract from the core {learning_objectives}. Refer to `modular-writing.txt` and `technical-voice.txt`
        to maintain consistency in tone and style.

    3.  **Optimize Tool Usage:** Consider how the use of {tools} (especially VS Code for technical topics) can be
        optimized to further engage learners. Suggest specific ways to leverage screen sharing, live coding demos,
        or collaborative coding exercises to enhance understanding and participation.

    4.  **Refine Knowledge Checks for Engagement:** Review the Knowledge Check questions provided by the SME and
        rephrase or augment them to be more engaging and thought-provoking. Consider incorporating varied question
        formats (e.g., open-ended, scenario-based) to encourage deeper processing of the material.

    5.  **Ensure Alignment with Learning Objectives:** Continuously ensure that all engagement strategies and
        interactive elements directly support the {learning_objectives} of each microlesson and the overall module.

    6.  **Format for Clarity and Impact:** Ensure the final output adheres to the formatting guidelines outlined in
        `markdown-document-structure.txt` and `modular-code.txt` (for technical content). Pay attention to visual
        hierarchy, use of formatting to highlight key information, and the overall readability of the enhanced
        content.

  expected_output: >
    An enhanced Markdown document that builds upon the content provided by the subject_matter_expert. This document
    should retain all the core information but feature significant improvements in learner engagement and
    interactivity for **all** microlessons. For each microlesson, the output should include:

    * **Learning Objective:** (Carried over from the SME's content)
    * **Enhanced Theory:**
        * Incorporation of suggestions for interactive questions or activities during the explanation.
        * Integration of relevant storytelling or narrative elements (where appropriate).
        * Clear indications of optimized {tool} usage (e.g., specific VS Code demonstration techniques).
    * **Enhanced Activity:**
        * Refined step-by-step instructions with potential for increased collaboration or individual exploration.
        * Clear Deliverable.
        * Engaging and thought-provoking Discussion Prompt.
    * **Enhanced Instructor Speaker Notes & Knowledge Checks:**
        * Augmentations to the speaker notes to guide the instructor in facilitating the new interactive elements
          and storytelling.
        * Rephrased or new Knowledge Check questions designed for higher engagement and deeper understanding.
    * **Formatting:** Consistent and effective use of Markdown formatting as per `markdown-document-structure.txt`
      and `modular-code.txt` to enhance clarity and visual appeal.

    The final output should represent a significant step towards creating a captivating and effective learning
    experience that resonates with the {learner_persona} and effectively supports the achievement of the
    {learning_objectives}.

learning_design_task:
  agent: learning_experience_designer
  output_file: output/enriched-microlesson-content.md
  description: >
    As the Learning Experience Designer, your task is to take the concise technical content developed by the
    subject_matter_expert and enrich it to create a more relatable and impactful learning experience for the
    {learner_persona}. Drawing upon your expertise in instructional design and the provided resources, you will
    layer in narrative elements, relatable moments, and practical learning opportunities. For each microlesson,
    you must:

    1.  **Weave in Narrative and Relatable Scenarios:** Identify key concepts and explore opportunities to introduce
        brief stories, real-world examples, or analogies that resonate with the {learner_persona}'s background and
        interests. These narratives should serve to illustrate complex ideas in an accessible and memorable way,
        as guided by `modular-writing.txt` and the tone defined in `technical-voice.txt`.

    2.  **Create "Aha Moments" through Relatability:** Analyze the technical content for potential points of confusion
        or abstraction. Develop relatable examples or analogies that bridge the gap between the abstract and the
        concrete, helping learners grasp the underlying principles. Refer to `creating-clear-exercises.txt` for
        guidance on building effective and understandable examples.

    3.  **Strategically Incorporate Interaction:** Review the existing activity and identify natural points to embed
        meaningful interactions and knowledge checks (discussion prompts, chat questions). Ensure these interactions
        are purposeful, reinforce the learning objectives, and cater to the {learner_persona}'s engagement style.

    4.  **Optimize for Practical Application:** Consider how the theoretical content can be directly connected to
        practical application and real-world problem-solving. Suggest ways to modify activities or add mini-challenges
        that allow learners to apply their knowledge in realistic scenarios, potentially leveraging the capabilities
        of {tools} as described in `modular-code.txt` for technical topics.

    5.  **Maintain Learning Focus:** Ensure that all added narrative elements, relatable moments, and interactive
        opportunities directly support the {learning_objectives} of the microlesson and contribute to a deeper
        understanding of the core concepts. Avoid adding elements that are purely for entertainment and do not
        serve a pedagogical purpose.

    6.  **Format for Clarity and Connection:** Ensure the final output adheres to the formatting guidelines in
        `markdown-document-structure.txt`, making the content visually appealing and easy to follow. Use formatting
        to highlight relatable examples and key takeaways.

    7. **IMPORTANT - Craft globally relevant content:** ensure that the content 
       is relevant to a global audience. Avoid using american-centric 
       examples or references that may not resonate with learners from
       different cultural backgrounds. Use examples that are universally 
       relatable and applicable to a diverse audience. Refrain from using idioms
       or colloquial expressions that may not translate well across cultures. Use the `creating-inclusive-and-globally-relevant-content.txt` document to help with this.

    8. **IMPORTANT - Ensure that no content is lost from the SME's
       content.** The SME's content should be the foundation of the final output. Your task is to **REFINE** the SME output, not cut any of the content provided by the SME. **DO NOT** summarize or cut any of the SME's content, **ONLY** modify it.

  expected_output: >
    An enriched Markdown document that builds upon the content provided by the subject_matter_expert. This document
    should feature a more narrative flow, clearly highlighted relatable examples and analogies, strategically placed
    interactive elements, and a strong emphasis on practical application for **all** microlessons. For each
    microlesson, the output should include:

    * **Learning Objective:** (Identical to the SME's content)
    * **Theory:**
        * Integration of narrative elements and real-world scenarios.
        * Inclusion of relatable examples and analogies to clarify complex concepts.
    * **Activity:**
        * Modifications to emphasize practical application and real-world relevance.
        * Strategically embedded interactive elements and discussion prompts.
        * Clear Deliverable.
    * **Instructor Speaker Notes & Knowledge Checks:**
        * Guidance for instructors on how to deliver the narrative elements and facilitate the interactive portions.
        * Knowledge Check questions that encourage learners to connect the content to real-world scenarios or their
          own experiences.
    * **Formatting:** Consistent and effective use of Markdown formatting as per `markdown-document-structure.txt`
      and `modular-code.txt` to enhance clarity and connection.

    The final output should represent a learning experience that is not only informative but also relatable, engaging,
    and clearly demonstrates the practical application of the {module_topic} for the {learner_persona}, ultimately
    leading to deeper understanding and retention.
